### ISSUE TITLE
[Bug Report] Compatiable for Bun/Other Engines

### ISSUE THREAD

**Issue by YunYouJun** [huankong-team/node-napcat-ts#54]
- https://github.com/oven-sh/bun/issues/2679

Bun has not supported `node:events` `on`.

Use `mitt` or `events` npm packge instead.

- https://www.npmjs.com/package/mitt
- https://www.npmjs.com/package/events

**Comment by huankong233** [comment]
> * [`events.on` is not implemented (async iterator for EventEmitter) oven-sh/bun#2679](https://github.com/oven-sh/bun/issues/2679)
> 
> Bun has not supported `node:events` `on`.
> 
> Use `mitt` or `events` npm packge instead.
> 
> * https://www.npmjs.com/package/mitt
> * https://www.npmjs.com/package/events

try the latest version(`0.2.22`)
