### ISSUE TITLE
quick_action的at_sender设置为true还是不生效

### ISSUE THREAD

**Issue by Admsec** [huankong-team/node-napcat-ts#71]
![image](https://github.com/user-attachments/assets/9fa93681-95b1-46ee-b2ed-531615495af9)
![image](https://github.com/user-attachments/assets/64fab76e-dbe1-4ea5-ae76-538cc0e67d0b)
![image](https://github.com/user-attachments/assets/dae9b1e5-071a-4ce4-803e-9422448380e6)

**Comment by huankong233** [comment]
是私聊吗，这个at只支持群聊

**Comment by Admsec** [comment]
> 是私聊吗，这个at只支持群聊

是私聊，好那我知道了

**Comment by huankong233** [comment]
> > 是私聊吗，这个at只支持群聊
> 
> 是私聊，好那我知道了

记得更新一下，改了一个类型，之前 `message.private.group` 也可以用 `at_sender` 已修复

**Comment by Admsec** [comment]
ok
